version: '3.8'

services:
  mariadb:
    container_name: php-laravel
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: php-laravel
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
        - app-network

volumes:
    db_data:

networks:
    app-network:
